# Generated by Django 4.0.3 on 2022-03-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newapp',
            fields=[
                ('name', models.CharField(max_length=70, blank=False, default='')),
                ('branch', models.CharField(max_length=200,blank=False, default='')),
                ('roll', models.IntegerField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
