# Generated by Django 4.0.3 on 2022-03-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('adhar_no', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
